// theme/home.ts: generate the Material `overrides/home.html` landing template.
//
// The docs home page is a REAL hero landing, not stock Material `grid cards`.
// The template is GENERATED (from the shared tokens + the emitter's inline-SVG
// compositions) so the hero illustration, architecture diagram, and section
// markup stay in lockstep with src/design-tokens.ts. It is a Jinja template
// that `extends "main.html"`; the authored prose (headline, sub, stat values)
// is passed via page.meta / front-matter on index.md so copy stays in content,
// while the LAYOUT + ART are generated here.
//
// Jinja note: this file emits Jinja2 control text ({% ... %}) verbatim; MkDocs
// renders it at build time. We keep the authored copy in index.md front matter
// (hero_headline, hero_sub, hero_eyebrow, stats[], etc.) and reference it with
// {{ page.meta.* }} so the template carries layout, not copy.

import { heroSvg, architectureSvg, svgIcon, brandMark } from './emit.ts';

const CHECK =
  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.1" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m5 12 4 4 10-10"/></svg>';
const CLOCK =
  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>';

/**
 * The architecture overlays + core label shown in the home illustration. These
 * are the charter overlays (truthful: opt-in verticals over a neutral core).
 * Kept here as the generated default; the template falls back to these when the
 * page front matter does not override them.
 */
const DEFAULT_OVERLAYS = ['Health', 'Education', 'ERP'] as const;
const DEFAULT_CORE = 'Neutral core';

/** Build the generated Jinja home template body. */
export function emitHomeTemplate(): string {
  const hero = heroSvg({
    coreLabel: DEFAULT_CORE,
    overlays: DEFAULT_OVERLAYS,
    label:
      'CuraOS architecture: opt-in vertical overlays (Health, Education, ERP) depend downward on one neutral core foundation.',
  });
  const arch = architectureSvg({
    coreLabel: DEFAULT_CORE,
    overlays: DEFAULT_OVERLAYS,
    caption:
      'Vertical overlays extend the neutral core and depend on it; the dependency never reverses.',
  });

  // The start-here cards: first is a wide feature lede, rest compact. Icons from
  // the shared library. Hrefs are RELATIVE doc links (navigation, not assets).
  const cards: ReadonlyArray<{
    icon: string;
    title: string;
    blurb: string;
    href: string;
    feature?: boolean;
  }> = [
    {
      icon: 'compass',
      title: 'Getting started',
      blurb:
        'The short tour: the core concepts, the live surfaces, and your first steps through the platform.',
      href: 'getting-started/',
      feature: true,
    },
    {
      icon: 'server',
      title: 'Install (self-host)',
      blurb: 'Deploy on Kubernetes with CNPG, Valkey, and an ingress controller.',
      href: 'install/',
    },
    {
      icon: 'layers',
      title: 'Architecture',
      blurb: 'The layered model, the charter principles, and the real stack.',
      href: 'architecture/',
    },
    {
      icon: 'puzzle',
      title: 'Apps guide',
      blurb: 'What each app does and where to find it across the suites.',
      href: 'apps/',
    },
    {
      icon: 'network',
      title: 'API reference',
      blurb: 'The service catalog and how to call the API gateway.',
      href: 'api/',
    },
    {
      icon: 'key',
      title: 'Auth setup',
      blurb: 'Pocket-ID OIDC and the Authorization Code with PKCE flow.',
      href: 'auth/',
    },
  ];

  const cardHtml = cards
    .map((c) => {
      const cls = c.feature ? 'home-card is-feature' : 'home-card';
      return (
        `      <a class="${cls}" href="{{ '${c.href}' | url }}">\n` +
        `        ${svgIcon(c.icon)}\n` +
        `        <div>\n` +
        `          <h3>${c.title}</h3>\n` +
        `          <p>${c.blurb}</p>\n` +
        `          <span class="go">Open<span class="ar" aria-hidden="true">&rarr;</span></span>\n` +
        `        </div>\n` +
        `      </a>`
      );
    })
    .join('\n');

  // The whole template. {% block ... %} hooks into Material's base.html via
  // main.html. Authored copy comes from page.meta with sensible literal
  // fallbacks so the page renders even if front matter is sparse.
  return `<!--
  GENERATED by src/theme/home.ts (bun run emit:theme). Do NOT hand-edit.
  Real hero landing for the CuraOS docs home, replacing the stock Material
  grid-cards. Layout + inline-SVG art are generated from the shared design
  tokens; authored copy is read from index.md front matter (page.meta.*).
-->
{% extends "main.html" %}

{% block content %}
<div class="cura-home">
  <section class="hero" aria-labelledby="cura-hero-h">
    <div class="hero-inner">
      <div class="hero-copy">
        <p class="hero-eyebrow"><span class="dot" aria-hidden="true"></span>{{ page.meta.hero_eyebrow or "Pre-1.0 / active buildout" }}</p>
        <h1 id="cura-hero-h">{{ page.meta.hero_headline or "Documentation for a composable, self-hosted-first care platform" }}</h1>
        <p class="sub">{{ page.meta.hero_sub or "Run it on your own infrastructure, compose only the pieces you need, and extend it through documented seams instead of forking it." }}</p>
        <div class="hero-cta-row">
          <a class="hero-cta hero-cta--primary" href="{{ 'getting-started/' | url }}">Get started<span class="ar" aria-hidden="true">&rarr;</span></a>
          <a class="hero-cta hero-cta--ghost" href="{{ 'architecture/' | url }}">Read the architecture</a>
        </div>
        {% if page.meta.stats %}
        <ul class="hero-stats" aria-label="At a glance">
          {% for s in page.meta.stats %}
          <li><span class="n">{{ s.value }}</span><span class="l">{{ s.label }}</span></li>
          {% endfor %}
        </ul>
        {% endif %}
      </div>
      <div class="hero-art" aria-hidden="false">
        ${hero}
      </div>
    </div>
  </section>

  <section class="home-section" aria-labelledby="cura-start-h">
    <p class="eyebrow">Start here</p>
    <h2 id="cura-start-h">Find your path in</h2>
    <p class="section-lead">Six entry points into the platform, from a first deploy to the API surface.</p>
    <div class="home-cards">
${cardHtml}
    </div>
  </section>

  <section class="home-section" aria-labelledby="cura-arch-h">
    <p class="eyebrow">Architecture</p>
    <h2 id="cura-arch-h">Generic core, opt-in overlays</h2>
    <p class="section-lead">Vertical overlays sit on top of one neutral foundation and depend downward on it. The dependency direction is the charter invariant, so the diagram reads as truthful architecture.</p>
    <figure class="home-arch">
      ${arch}
      <figcaption>Health, Education, and ERP are opt-in overlays that extend the neutral core; they never reverse the dependency.</figcaption>
    </figure>
  </section>

  <section class="home-section" aria-labelledby="cura-status-h">
    <p class="eyebrow">Honest status</p>
    <h2 id="cura-status-h">Shipped today, and on the roadmap</h2>
    <p class="section-lead">CuraOS is pre-1.0 and in active development. Capability claims that are not yet generally available are framed as design intent, not shipped behavior.</p>
    <div class="home-status">
      <div class="col shipped">
        <h3><span class="dot" aria-hidden="true"></span>Running today</h3>
        <ul>
          <li>${CHECK}<span>Frontend apps on their own subdomains, one design system, dark mode and Arabic RTL that persist.</span></li>
          <li>${CHECK}<span>Neutral core plus HealthStack and personal/business variants behind an API gateway.</span></li>
          <li>${CHECK}<span>OIDC single sign-on through Pocket-ID (Authorization Code with PKCE), brokered into a session.</span></li>
          <li>${CHECK}<span>Self-hosted runtime: Kubernetes, CNPG-managed PostgreSQL, Valkey, and an ingress controller.</span></li>
        </ul>
      </div>
      <div class="col road">
        <h3><span class="dot" aria-hidden="true"></span>On the roadmap</h3>
        <ul>
          <li>${CLOCK}<span>Read and write endpoints filling in across every service along the milestone plan.</span></li>
          <li>${CLOCK}<span>The public demo tenant and the air-gap install bundle.</span></li>
          <li>${CLOCK}<span>Education and ERP overlays beyond the HealthStack first mover.</span></li>
          <li>${CLOCK}<span>The 1.0 release: a stable, versioned contract surface.</span></li>
        </ul>
      </div>
    </div>
  </section>

  <section class="home-section home-prose" aria-label="Overview">
    <div class="md-typeset">
      {{ page.content }}
    </div>
  </section>
</div>
{% endblock %}
`;
}

/**
 * The `overrides/main.html` template: extends Material base.html and is the
 * parent the generated home.html extends. It is intentionally thin: it only
 * declares the brand mark partial hook is unnecessary (extra.css drives chrome),
 * so we keep it minimal and stable. Kept generated for a single source.
 */
export function emitMainTemplate(): string {
  return `<!--
  GENERATED by src/theme/home.ts (bun run emit:theme). Do NOT hand-edit.
  Thin Material override parent. The generated home.html extends THIS so the
  custom landing inherits Material's header/footer/search while the rest of the
  skin is driven by the bundled extra.css. The brand mark is available as an
  inline SVG string for any future header injection.
-->
{% extends "base.html" %}
`;
}

/** Expose the brand mark for any consumer that wants the header glyph. */
export { brandMark };
